export enum FormFieldType {
  INPUT = "input",
  TEXTAREA = "textarea",
  CHECKBOX = "checkbox",
  RADIO = "Radio",
  SELECT = "select",
  DATE_PICKER = "datePicker",
  DATE_PICKER_NEW = "datePicker_new",
  DATETIME_PICKER = "datetimePicker",
  NUMBER = "number",
  DATE_INPUT = "dateInput",
  SELECT_SUGGEST = "selectSuggest",
}

// Loại icd chính hoặc là icd kèm theo
export enum ICDType {
  MAIN = "main", // icd chính
}

export enum HttpStatus {
  SUCCESS = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
}

export enum DisableStatus {
  ENABLE = "ENABLE",
  DISABLE = "DISABLE",
}

export const DisableStatusLabel: Record<DisableStatus, string> = {
  [DisableStatus.ENABLE]: "Hoạt động",
  [DisableStatus.DISABLE]: "Dừng",
};

export enum PharImportStatus {
  "PENDING" = "PENDING",
  "COMPLETED" = "COMPLETED",
  "APPROVED" = "APPROVED",
  "CANCELLED" = "CANCELLED",
}

export const PharImportStatusLabel: Record<PharImportStatus, string> = {
  [PharImportStatus.PENDING]: "Chưa xử lý",
  [PharImportStatus.COMPLETED]: "Đã xử lý",
  [PharImportStatus.APPROVED]: "Đã duyệt",
  [PharImportStatus.CANCELLED]: "Đã huỷ",
};

export enum AppPermission {
  // Nhóm nhận bệnh
  RECEPTION = "RECEPTION",
  VIEW_CONSULTATION_HISTORY = "VIEW_CONSULTATION_HISTORY",

  // Nhóm khám bệnh
  CONSULTATION = "CONSULTATION",
  CREATE_PRESCRIPTION = "CREATE_PRESCRIPTION",
  GET_PRESCRIPTION = "GET_PRESCRIPTION",
  GET_PATIENT_INFO = "GET_PATIENT_INFO",
  UPDATE_PATIENT_INFO = "UPDATE_PATIENT_INFO",

  // Nhóm bệnh án
  OUT_PATIENT_EMR = "OUT_PATIENT_EMR",

  // Nhóm kho dược
  CREATE_IMPORT_ORDER = "CREATE_IMPORT_ORDER",
  UPDATE_IMPORT_ORDER = "UPDATE_IMPORT_ORDER",
  APPROVED_IMPORT_ORDER = "APPROVED_IMPORT_ORDER",
  VIEW_IMPORT_ORDER = "VIEW_IMPORT_ORDER",
  PAYMENT = "PAYMENT",
  PRESCRIPTION_PAYMENT = "PRESCRIPTION_PAYMENT",

  // Nhóm quản trị danh mục kho dược
  DRUG_STORE_MANAGEMENT = "DRUG_STORE_MANAGEMENT",
  GET_LIST_STORE = "GET_LIST_STORE",
  CREATE_STORE = "CREATE_STORE",
  UPDATE_STORE = "UPDATE_STORE",
  DELETE_STORE = "DELETE_STORE",
  DRUG_SUPPLIER_MANAGEMENT = "DRUG_SUPPLIER_MANAGEMENT",

  // Nhóm báo cáo
  REPORT_MENU = "REPORT_MENU",
  STOCK_TRANSACTION_REPORT = "STOCK_TRANSACTION_REPORT",
  STOCK_CARD_REPORT = "STOCK_CARD_REPORT",
  CONSULTATION_REPORT = "CONSULTATION_REPORT",

  // Nhóm quản trị người dùng
  USER_MANAGEMENT = "USER_MANAGEMENT",
  GET_LIST_USER = "GET_LIST_USER",
  CREATE_USER = "CREATE_USER",
  UPDATE_USER = "UPDATE_USER",
  DELETE_USER = "DELETE_USER",
  UPDATE_PERMISSION = "UPDATE_PERMISSION",
  USER_ROLE_MANAGEMENT = "USER_ROLE_MANAGEMENT",
  GET_ROLE_INFO = "GET_ROLE_INFO",
  CREATE_USER_ROLE = "CREATE_USER_ROLE",
  UPDATE_USER_ROLE = "UPDATE_USER_ROLE",
  DELETE_USER_ROLE = "DELETE_USER_ROLE",
  GET_LIST_PERMISSION = "GET_LIST_PERMISSION",

  // Quản trị chi nhánh
  TENANT_MANAGEMENT = "TENANT_MANAGEMENT",
  GET_LIST_TENANT = "GET_LIST_TENANT",
  CREATE_TENANT = "CREATE_TENANT",

  // Nhóm quản trị hệ thống
  SYSTEM_MANAGEMENT = "SYSTEM_MANAGEMENT",
}
