import { NavItem } from "@/types";

import AcceptSurgeryTicketForm from "@/components/surgery/AcceptSurgeryTicketForm";
import SurgeryTicketForm from "@/components/surgery/SurgeryTicketForm";
import ProcedureTicketForm from "@/components/surgery/ProcedureTicketForm";
import { AppPermission } from "./enum";

export const navItems: NavItem[] = [
  {
    title: "Tiếp nhận",
    href: "/reception",
    icon: "user",
    label: "",
    permission: AppPermission.RECEPTION,
    prefix: "reception",
    level: 1,
  },
  {
    title: "Khám bệnh",
    href: "/concultation",
    icon: "user",
    label: "",
    permission: AppPermission.CONSULTATION,
    prefix: "concultation",
    level: 1,
  },
  {
    title: "Bệnh án",
    href: "",
    icon: "user",
    label: "",
    permission: AppPermission.OUT_PATIENT_EMR,
    prefix: "out-emr",
    level: 1,
    childrens: [
      {
        title: "Phẫu thuật - Thủ thuật",
        href: "",
        icon: "user",
        label: "",
        permission: "",
        prefix: "surgery",
        level: 2,
        childrens: [
          {
            title: "Giấy cam kết phẫu thuật",
            component: AcceptSurgeryTicketForm,
            label: "Nhập thông tin phiếu cam kết phẫu thuật",
            prefix: "accept-surgery-ticket",
            permission: "",
            level: 3,
          },
          {
            title: "Phiếu phẫu thuật",
            component: SurgeryTicketForm,
            label: "Phiếu phẫu thuật",
            prefix: "surgery-ticket",
            permission: "",
            level: 3,
          },
          {
            title: "Phiếu thủ thuật",
            component: ProcedureTicketForm,
            label: "Phiếu thủ thuật",
            prefix: "procedure-ticket",
            permission: "",
            level: 3,
          },
        ],
      },
    ],
  },
  {
    title: "Kho dược",
    href: "",
    icon: "user",
    label: "",
    permission: AppPermission.VIEW_IMPORT_ORDER,
    prefix: "drug-store",
    level: 1,
    childrens: [
      {
        title: "Nhập kho",
        icon: "user",
        href: "/drug-store/phar-import",
        label: "",
        permission: AppPermission.VIEW_IMPORT_ORDER,
        prefix: "/drug-store/phar-import",
        level: 2,
      },
      {
        title: "Danh mục",
        icon: "user",
        href: "",
        label: "",
        permission: AppPermission.DRUG_STORE_MANAGEMENT,
        prefix: "",
        level: 2,
        childrens: [
          {
            title: "Kho / quầy",
            href: "/drug-store/stores",
            label: "Danh sách kho / quầy",
            prefix: "/drug-store/store",
            permission: AppPermission.DRUG_STORE_MANAGEMENT,
            level: 3,
          },
          {
            title: "Nhà cung cấp",
            href: "/drug-store/suppliers",
            label: "Danh sách nhà cung cấp",
            prefix: "/drug-store/suppliers",
            permission: AppPermission.DRUG_SUPPLIER_MANAGEMENT,
            level: 3,
          },
        ],
      },
    ],
  },
  {
    title: "Thu tiền",
    href: "",
    icon: "user",
    label: "",
    permission: AppPermission.PAYMENT,
    prefix: "cashier",
    level: 1,
    childrens: [
      // {
      //   title: "Dịch vụ",
      //   href: "/payment/service",
      //   icon: "user",
      //   label: "",
      //   permission: AppPermission.CASHIER,
      //   prefix: "cashier",
      //   level: 2,
      // },
      {
        title: "Toa thuốc",
        href: "/payment/prescription",
        icon: "user",
        label: "",
        permission: AppPermission.PRESCRIPTION_PAYMENT,
        prefix: "cashier",
        level: 2,
      },
    ],
  },
  {
    title: "Report",
    href: "",
    icon: "user",
    label: "",
    prefix: "report",
    level: 1,
    permission: AppPermission.REPORT_MENU,
    childrens: [
      {
        title: "Khám bệnh",
        href: "",
        label: "Khám bệnh",
        prefix: "report",
        permission: AppPermission.CONSULTATION_REPORT,
        level: 2,
        childrens: [
          {
            title: "Báo cáo lượt khám",
            href: "/report/consultation",
            label: "Báo cáo lượt khám",
            prefix: "report",
            permission: AppPermission.CONSULTATION_REPORT,
            level: 3,
          },
        ],
      },
      {
        title: "Kho dược",
        href: "",
        label: "Kho dược",
        prefix: "report",
        permission: AppPermission.STOCK_TRANSACTION_REPORT,
        level: 2,
        childrens: [
          {
            title: "Báo cáo nhập xuất tồn",
            href: "/report/drug-store/stock-transaction",
            label: "Báo cáo nhập xuất tồn",
            prefix: "report",
            permission: AppPermission.STOCK_TRANSACTION_REPORT,
            level: 3,
          },
          {
            title: "Báo cáo thẻ kho",
            href: "/report/drug-store/stock-card",
            label: "Báo cáo thẻ kho",
            prefix: "report",
            permission: AppPermission.STOCK_CARD_REPORT,
            level: 3,
          },
        ],
      },
    ],
  },
  {
    title: "Quản trị",
    href: "#",
    icon: "kanban",
    label: "kanban",
    prefix: "Quản trị",
    permission: AppPermission.SYSTEM_MANAGEMENT,
    level: 1,
    childrens: [
      {
        title: "Quản lý phòng khám",
        href: "/administrator/clinic_management",
        label: "Quản lý phòng khám",
        prefix: "administrator",
        permission: AppPermission.TENANT_MANAGEMENT,
        level: 2,
      },
      {
        title: "Quản lý người dùng",
        href: "/administrator/user_management",
        label: "Quản lý người dùng",
        prefix: "administrator",
        permission: AppPermission.USER_MANAGEMENT,
        level: 2,
      },
      {
        title: "Quản lý quyền",
        href: "/administrator/role_management",
        label: "Quản lý quyền",
        prefix: "administrator/role_management",
        permission: AppPermission.USER_ROLE_MANAGEMENT,
        level: 2,
      },
    ],
  },
];
