import z from "zod";

export const PatientFormValidation = z.object({
  patientName: z.string().min(3, "Vui lòng nhập tên bệnh nhân"),
  gender: z.enum(["male", "female"], {
    message: "Vui lòng chọn giới tính",
  }),
  dayOfBirth: z.string().optional(),
  monthOfBirth: z.string().optional(),
  yearOfBirth: z.string().optional(),
  age: z.string().optional(),
  ethniCode: z.string().optional(),
  ethnic: z.string().optional(),
  nationality: z.string().optional(),
  nationalityCode: z.string().optional(),
  educationCode: z.string().optional(),
  careerCode: z.string().optional(),
  education: z.string().optional(),
  career: z.string().optional(),
  careerPlace: z.string().optional(),
  isCnv: z.boolean().default(false),
  patientObject: z.string().optional(),
  patientObjectCode: z.string().optional(),
  address: z.string().optional(),
  province: z.string().optional(),
  district: z.string().optional(),
  ward: z.string().optional(),
  phoneNumber: z.string().optional(),
  relatives: z.string().optional(),
  checkInMonth: z.string().optional(),
  checkInDay: z.string().optional(),
  checkInTime: z.string().optional(),
  checkInDepartment: z.string().optional(),
  examinationType: z.string().optional(),
  introductionPlaceCode: z.string().optional(),
  introductionText: z.string().optional(),
  checkInPhoneNumber: z.string().optional(),
  examinationNumber: z.string().optional(),
  icdMoveText: z.string().optional(),
  doctorName: z.string().optional(),
  icdMoveCode: z.string().optional(),
  icdMoveName: z.string().optional(),
  icdEmergencyText: z.string().optional(),
  icdEmergencyCode: z.string().optional(),
  icdEmergencyName: z.string().optional(),
  icdTreatmentText: z.string().optional(),
  icdTreatmentCode: z.string().optional(),
  icdTreatmentName: z.string().optional(),
});
